trigger:
    branches:
        include:
            - development

pool:
    vmImage: 'ubuntu-latest'

variables:
    buildConfiguration: 'development'
    distFolder: 'dist/plan-sphere-frontend/browser'

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: '20.x'

    - script: |
          npm install -g @angular/cli
          npm install
      displayName: 'Install Angular CLI and dependencies'

    - script: npm run build-dev
      displayName: 'Build Angular App'

    - task: CopyFiles@2
      inputs:
          contents: '$(Build.ArtifactStagingDirectory)/$(distFolder)/**'
          targetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Copy Files to Staging Directory'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact'
      inputs:
          artifactName: 'drop'
          targetPath: '$(Build.ArtifactStagingDirectory)'

    - task: AzureWebApp@1
      inputs:
          azureSubscription: 'Azure for Students(24a7ebc5-4993-4fdf-aefd-15a323aa8a10)'
          appName: 'plansphere-frontend-development'
          package: '$(Build.ArtifactStagingDirectory)'
          appType: 'webAppLinux'
      displayName: 'Deploy to Azure Web App'
